# Save the switched spawn usage data to a file to load for specific players after server restart.
remember-toggled-spawns-to-file: true

# How many seconds have to wait for a player to be teleported?
# Leave at 0 if you want to teleport immediately.
# This will be ignored with "setthespawn.bypass.cooldown" permission for specific players
teleport-delay: 0

# This allows to send the messages repeatedly when the player starts
# teleporting, otherwise it will sends the message once only.
teleport-message-repeater: false

# Displaying progress bar after the player started to teleport.
progress-bar:
  enable: false

  bar-size: 30.0

  # Update frequency
  fast: 2

  # Teleport progress display mark
  mark: "\u258B"

  # Color to display the progress of teleporting
  done-color: "&a&l"

  # Color to display the progress of the waiting time
  not-done-color: "&c&l"

  message-format: "&aTeleporting in:&7&l [%output%&7&l]&6 (&8%time%&6)"

# If players execute spawn command they will be teleported
# to world spawn in case if spawn is not set.
teleport-to-world-spawn-if-spawn-not-found: false

# Teleport the player to the default set world spawn?
# If this true, it will ignores the spawn location,
# join spawn and teleports to the world spawn location.
teleport-to-world-spawn: false

# Teleport to the player's bed location, if exist.
# This option also works with anchor spawn if exist.
teleport-to-bed-spawn: false

# Do include operator players in teleporting to teleport them?
# This is only valid when someone wants to teleport each player.
teleport-op-players: false

# A player teleported to the spawn, how many seconds to protect the player from damage?
# Leave it at 0 to disable
no-damage-time: 0

# Teleports automatically to spawn, when a player afk status is true.
# Requires Essentials!
auto-teleport-to-spawn-when-player-afk: false

# Use separate worlds?
# If enabled, the behaviour of the spawn will also change.
# All worlds spawn must be set, if no players will not be teleported.
# This will changes the spawn settings in the spawns file.
per-world-spawn: false

# In which worlds can spawn not be set and used?
disabled-worlds:
#- world_the_end

# Prevent spawn command executing when a player in combat.
disable-spawn-in-pvp:
  enable: false

  # Waiting time to use the spawn again.
  time: 5

  # Message when you attack a player or attack yourself.
  message: "&cNow you can not teleport to spawn because you're still fighting with a player."

# Check if the player is in flying mode?
# If it is true, players can teleport while flying.
# If it is false, it will cancel the teleport delay.
# This ignores with setthespawn.bypass.fly permission.
allow-spawn-when-flying: true

# Allows to the player to teleport to the spawn if the player is in minecart.
# This can be bypassed with setthespawn.bypass.minecart permission.
allow-spawn-when-is-in-minecart: true

# Allows to the player to teleport to the spawn if the player is in boat.
# This can be bypassed with setthespawn.bypass.boat permission.
allow-spawn-when-is-in-boat: true

# Prevent spawn teleport when player is in fire?
# This ignores with setthespawn.bypass.fire permission.
prevent-spawn-when-player-is-in-fire: false

# When a player presses the SHIFT button while teleporting, and sits in snake mode,
# will it cancel the teleportation?
# This ignores with setthespawn.bypass.sneak permission.
check-sneak-while-teleport:
  enable: false
  message: "&cTeleporting is cancelled because snake mode is enabled."

# Cost for /spawn command executing or sign interacting.
# For this, requires Vault plugin.
spawn-cost:
  # Bypass permission to allow teleporting without payment.
  # This will be ignored if this empty.
  permission: setthespawn.bypass.spawncost

  # The amount of cost to be paid.
  cost: 0.0

  # Sign interaction price
  sign:
    # Bypass permission to allow teleporting via sign without payment.
    # This will be ignored if this empty.
    permission: setthespawn.bypass.signcost

    # The amount of cost to be paid.
    cost: 0.0

cancel-teleport:
  # How many seconds does the player have to wait to use the spawn command
  # again when the player moved during teleport time? (bypass permission: setthespawn.bypass.spawndelay)
  # Move includes damage, jump and any type of movement.
  spawn-command-delay-after-move: 0

  # Player was moved while teleporting.
  move:
    enable: true

    teleport-canceled: "&cTeleport cancelled, you can't move!"

    # Bypass permission to allow movement while teleporting.
    permission: setthespawn.bypass.movement

    # Play sound when a player moved while teleporting.
    play-sound:
      # SOUND_TYPE, volume, pitch
      #type: BLOCK_ENDER_CHEST_CLOSE, 8, 1

    # The player should pay for movement while teleporting.
    pay-if-moved:
      # The amount of cost to be paid.
      cost: 0.0

      # The permission to bypass movement payment.
      permission: setthespawn.bypass.spawn.movedcost

  # Player was jump while teleporting.
  jump:
    enable: true

    teleport-canceled: "&cTeleport cancelled, you can't jump!"

    # Bypass permission to allow jump while teleporting.
    permission: setthespawn.bypass.jump

    # Play sound when a player jump while teleporting.
    play-sound:
      # SOUND_TYPE, volume, pitch
      #type: BLOCK_WOODEN_DOOR_CLOSE

    # The player should pay for jump payment.
    pay-if-jumped:
      # The amount of cost to be paid.
      cost: 0.0

      # The permission to bypass jump while teleporting.
      permission: setthespawn.bypass.spawn.jumpedcost

  # When the player is attacked somebody while teleporting.
  damage:
    enable: true

    teleport-canceled: "&cTeleport cancelled, you are in combat!"

    # Bypass permission to allow player damaging while teleporting.
    permission: setthespawn.bypass.damage

    # Play sound when a player attacked someone while teleporting.
    play-sound:
      # SOUND_TYPE, volume, pitch
      #type: BLOCK_LEVER_CLICK, 8, 1

    # Should the player pay for damage while teleporting?
    pay-if-damage:
      # The amount of cost to be paid.
      cost: 0.0

      # The permission to bypass damage payment.
      permission: setthespawn.bypass.spawn.damagecost

# Play effect after the player is teleported?
teleport-effect:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
  # EFFECT_TYPE, duration
  #effect: ENDER_SIGNAL, 10

# Play sound after the player is teleported?
teleport-sound:
  # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Sound.html
  # SOUND_TYPE, volume, pitch
  #sound: ENDERMAN_TELEPORT, 10, 1

# Launch firework when the player teleported
launch-firework:
  enable: false

  # This will fixes that issue when all the entities got damage after
  # player teleportation and launching a firework.
  # This calculates 15 radius around player to make sure the entities not get any damage.
  # If you have issues with this, then disable it.
  fix-entity-damage-after-teleportation: true

  random: true
  flicker: true
  trail: true

  # https://hub.spigotmc.org/javadocs/bukkit/org/bukkit/FireworkEffect.Type.html
  type: STAR

  # Colors 0 - 255
  colors:
  - 229,0,0
  - 0,80,0
  - 0,0,103

  # Does the firework explode instantly?
  # If this enabled power setting are ignored.
  instant-explode: false

  # The power to launch the firework.
  power: 1

title:
  # When you have started teleporting, a title will also be displayed.
  start-spawn:
    #title: "&aTeleporting in"
    #subtitle: "&6%seconds%&a seconds"

    # The title times to be displayed, stay and removing from the screen. (In ticks)
    # fadeIn, stay, fadeOut
    times: 10, 30, 60

  # When the player has teleported to the spawn and displays the title.
  end-spawn:
    #title: "&3Teleport"
    #subtitle: "&asuccess!"

    times: 10, 30, 60

  # When a player moves while teleporting.
  player-moved:
    #title: "&cYou moved!"
    #subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

  # When a player jumps while teleporting.
  player-jumped:
    #title: "&cYou jumped!"
    #subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

  # When player are attacked somebody while teleporting.
  player-damage:
    #title: "&cA player was attacked!"
    #subtitle: "&eTeleport cancelled."

    times: 10, 30, 50

# When the player reached the given amount of void height will it teleport to the spawn?
void-on-spawn:
  enable: false

  # At that point, the player will be teleported to the spawn.
  # Example: 5 - so Y:5
  height: 0

  # true - player will be protected from fall distance hurt.
  # false - player will not be protected from fall distance hurt.
  fall-distance: true

  # The list of disabled worlds where player shouldn't teleport to the set of spawn.
  disabled-worlds:
    # If enabled, the world names should target the set of spawn world.
    # For example, if you have set spawn in world1, and disabled world_nether,
    # players are not teleports to world1 spawn if falls into void.
    use-target-spawn-worlds: false
    list:
    #- end

  # Play effect after player teleported from void?
  teleport-effect:
    # https://hub.spigotmc.org/javadocs/spigot/org/bukkit/Effect.html
    #effect: ENDER_SIGNAL, 15

  # Message when the player teleported from void.
  message: ""

# Perform commands after player teleport
teleport-on-command:
  # Use player & console arguments for first.
  # You can use %player% & %world% placeholders.
  commands:
  #- "player: money"
  #- "player: kit"
  #- "console: eco take %player% 50"
  #- "console: money"

spawn-teleport:
  player-join: false
  player-first-join: false

  # Teleport the player if died?
  respawn: false

  # Respawn player at their bed spawn if exist?
  respawn-at-bed: false

  # (1.16+) Respawn player at anchor?
  respawn-at-anchor: true

spawn-sign:
  # Allows you to create and use spawn sign
  enable: true

  # Save signs data automatically to a file when a sign was placed?
  save-sign-data: false

  # If the player does not have permission to create a sign.
  no-permission-create-sign:
    # true - the sign that was placed will break
    # false - the sign will not break
    break-sign: false

    # If the above option "break-sign" is disabled, some text will set in sign
    setline:
      lines:
      - "&cYou do not have"
      - "&cpermission"
      - "&cto create"
      - "&ca sign!"

  # If the spawn is not set what to display in sign
  no-spawn:
  - "&c[Spawn]"
  - "%text%"
  - "%text%"
  - "%text%"

  # If the spawn is exist, what to display in sign
  spawn-created:
    lines:
    - "&9[Spawn]"
    - "%text%"
    - "%text%"
    - "%text%"

    everybody:
    - "&9[Spawn]"
    - "%all%"
    - "%text%"
    - "%text%"

    per-world:
      lines:
      - "&9[Spawn]"
      - "&6%world%"
      - "%text%"
      - "%text%"

      everybody:
      - "&9[Spawn]"
      - "%all%"
      - "%world%"
      - "%text%"

# Enable the gui setup?
enable-gui: true

# How many rows should the GUI have?
# This multiplies the specified number by 9, thus creating the GUI correctly.
gui-rows: 1

# What should the name of the GUI be?
gui-name: "&5Spawn settings"

# All setup GUI items are set here
# Slot starts at 0 and end at 53 for a size 54 inventory.
items:
  slot-2:
    item: oak_sign
    name: "&3Setspawn"
    lore:
    - "&7------------"
    - "&aSet spawn command."
    - "&7------------"
    command: setspawn
  slot-4:
    item: ENDER_PEARL
    name: "&6Teleport"
    lore:
    - "&7------------"
    - "&aTeleport to the spawn."
    - "&7------------"
    command: spawn
  slot-6:
    item: bone
    name: "&4Delete spawn"
    lore:
    - "&7------------"
    - "&5Delete spawn location."
    - "&7------------"
    command: delspawn

# Check for updates
check-update: true

# Download releases to "releases" folder
# This only works if the "check-update" is true.
download-updates: true

# Log plugin messages into console.
logconsole: true

# DO NOT CHANGE THIS!
config-version: 12
